### PR TITLE
Z-score on the fly calculation

### PR DESCRIPTION
**Pull request by charlotte-raillere**
The principle of the enhancement is to be able to choose a z-score on the fly calculation (z-score calculated for the cohort selected) and supersede the z-score calculation done at the data loading step (z-score calculated based on the whole cohort loaded).
This option appears in the advanced workflow and is available for the following analyses: Heatmap, K-Means Clustering, Hierarchical Clustering, Marker Selection and PCA.

### CODE REVIEW

**Comment by cataphract** [comment]
@timdo @RianneJ Can you review this? For me, it seems at least that the calculation should be refactored into a separate file/function, but I can't comment on whether the feature is sound.

**Comment by cataphract** [comment]
Apart from some ws issues, the rest seems fine.

But I have a related question. It seems you calculate the z-score from the log-intensity, rather than from the raw intensity. Is this the way it is now in the data loading procedures for the precalculated value?

**Comment by charlotte-raillere** [comment]
@cataphract Yes, the z-score is also calculated from log-intensity during data loading

**Comment by charlotte-raillere** [comment]
Hi,
Is there still some problems/questions preventing from merging this pull request?

**Comment by cataphract** [comment]
I'm merging since the only objections seem to be in the vein of "the current procedure is flawed and this is the same". That can be handled later; this just keeps the status quo.

**Pull request merged**
